name: awakening
description: "An RPG-like life game"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  firebase_ai: ^3.1.0
  intl: ^0.20.2
  flutter_svg: ^2.2.0

  # For device and package info
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/service_account.json
    - assets/icons/
